# -*- coding: utf-8 -*-
"""colab set up

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A9s571_1DGWMeUcApKMDYxiWSZdfcIu0
"""

import pandas as pd
import numpy as np

print("Data Analysis Environment Ready!")